name: Publish artifacts
on:
  release:
    types: [published]


env:
  VERSION: ${{ github.event.release.tag_name }}

permissions:
  contents: "write"
  id-token: "write"
  packages: "write"

jobs:
  build-and-release:
    name: Build and release package
    uses: navikt/bidrag-workflow/.github/workflows/maven_publish.yaml@main
    with:
      version: ${{ env.VERSION }}
    secrets: inherit

  commit-version-file:
    name: Commit version
    needs: build-and-release
    if: ${{ needs.build-and-release.outputs.published == 'true' }}
    uses: ./.github/workflows/commit-version-file.yaml
    with:
      version: ${{ needs.build-and-release.outputs.version }}
    secrets: inherit