name: Release package
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Versjon på pakken som skal publiseres

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setting version
        run: |
          mvn versions:set -DnewVersion="${{ inputs.version }}"
          mvn versions:commit
      - name: Deploy to Github Package
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Release package with version ${{ inputs.version }}"
          mvn --settings .github/.m2/maven-settings.xml source:jar-no-fork deploy -DskipTests=true -Dmaven.wagon.http.pool=false -DdeployAtEnd=true