name: Publish artifacts
on:
  release:
    types: [published]
env:
  VERSION: ${{ github.event.release.tag_name }}

permissions:
  contents: "write"
  id-token: "write"
  packages: "write"

jobs:
  build-and-release:
    name: Build and release package
    uses: navikt/bidrag-workflow/.github/workflows/release_package/publish_dispatcher.yaml@workflow_publish
    with:
      version: ${{env.VERSION}}
    secrets: inherit