name: Publish artifacts
on:
  release:
    types: [published]
env:
  VERSION: ${{ github.event.release.tag_name }}

permissions:
  contents: "write"
  id-token: "write"
  packages: "write"

jobs:
  build-and-release:
    name: Build and release package
    uses: navikt/bidrag-workflow/.github/workflows/maven_publish.yaml@main
    with:
      version: ${{env.VERSION}}
    secrets: inherit

  commit-version-file:
    name: Commit version
    runs-on: ubuntu-latest
    needs: build-and-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commit version
        env:
          versionfile_path: bidrag-inntekt/src/main/resources/versjon.txt
        run: |
          git config user.name "Automatisk versjon comitter"
          git config user.email "actions@users.noreply.github.com"
          export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
          export APP_VERSION=(${{env.VERSION}}_$GIT_COMMIT_HASH)
          echo $APP_VERSION > ${{env.versionfile_path}}
          echo ⚙️ Opprettet versjonfil med versjon $APP_VERSION
          git add ${{env.versionfile_path}}
          git commit -m "Oppdater versjonfil til $APP_VERSION"
          git push origin HEAD:versjon_fil