name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  build-release:
    name: "Build and release package"
    uses: navikt/bidrag-workflow/.github/workflows/maven_release_drafter.yaml@main
    secrets: inherit
    with:
      publish: true

  commit-version-file:
    name: Commit version
    needs: build-release
    if: ${{ needs.build-release.outputs.published == 'true' }}
    uses: ./.github/workflows/commit-version-file.yaml
    with:
      version: ${{ needs.build-release.outputs.version }}
    secrets: inherit