name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  build-release:
    name: "Build and release package"
    uses: navikt/bidrag-workflow/.github/workflows/maven_release_drafter.yaml@main
    secrets: inherit
    with:
      publish: true

  commit-version-file:
    name: Commit version
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Commit version
        run: |
          git config user.name "Automated Version Committer"
          git config user.email "actions@users.noreply.github.com"
          export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
          export APP_VERSION=(${{env.VERSION}}_$GIT_COMMIT_HASH)
          echo $VERSION > bidrag-inntekt/src/main/resources/version.txt
          echo Opprettet versjon fil med versjon $APP_VERSION
          git add bidrag-inntekt/src/main/resources/version.txt
          git commit -m "Oppdater versjon fil til $APP_VERSION"
          git push origin HEAD:versjon_fil