name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  build-release:
    name: "Build and release package"
    uses: navikt/bidrag-workflow/.github/workflows/release_package/release_drafter.yaml@workflow_publish
    secrets: inherit
